# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'TodoList' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"
  pod 'MGSwipeTableCell', '~> 1.5.1'

  # Pods for TodoList

  target 'TodoListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TodoListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
