# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pretty Weather' do
  use_frameworks!
  inhibit_all_warnings!

  # Pods for Pretty Weather
  pod 'Cartography', :git => "https://github.com/robb/Cartography.git"
  pod 'Alamofire'
  pod 'SwiftyJSON', '~> 4.0.0-alpha'
  pod 'WeatherIconsKit', :git => "https://github.com/gscalzo/WeatherIconsKit"
  pod 'FlickrKit'
  pod 'FXBlurView'
  pod 'LatoFont', :git => "https://github.com/gscalzo/LatoFont.git"

  target 'Pretty WeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Pretty WeatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
